Repository linux-system-roles/network, pull requests merged in 2021-01, with the labels that each got.

#330 Collections - workaround for the module_utils path finding issue in ansible 2.9
  library/network_connections.py
  module_utils/network_lsr/nm/__init__.py
  module_utils/network_lsr/nm/active_connection.py
  module_utils/network_lsr/nm/client.py
  module_utils/network_lsr/nm/provider.py
Labels: Waiting_rebase

#336 add ansible-lint to github actions
  .github/workflows/tox.yml
Labels: Wait_Submitter

#302 nm provider: Refactor the volatilize action of network connection
  library/network_connections.py
  module_utils/network_lsr/nm/connection.py
  module_utils/network_lsr/nm/provider.py
Labels: Wait_Review

#340 Support dns-options in network role
  README.md
  examples/eth_dns_support.yml
  library/network_connections.py
  module_utils/network_lsr/argument_validator.py
  tests/ensure_provider_tests.py
  tests/playbooks/tests_eth_dns_support.yml
  tests/tests_eth_dns_support_nm.yml
  tests/unit/test_network_connections.py
Labels: Wait_Review
